version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3310:3306'
    environment:
       MYSQL_DATABASE: 'boilerplate'
       MYSQL_USER: 'test_user'
       MYSQL_PASSWORD: 'test_password'
       MYSQL_ROOT_PASSWORD: 'root'
  web:
    build: .
    command: bash -c '
      ./wait-for-it.sh db:3306
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8090'
    volumes:
      - .:/myapp
    ports:
      - '8090:8090'
    depends_on:
      - db
